POST http://localhost:4000/courses-api/createCourse
Content-Type: application/json

{
    "id":7015,
    "courseTitle":"react js",
    "courseSylabus":"react",
    "courseFee":18000,
    "courseDuration":"20 days",
    "courseSd-Ed":"2024-02-03",
    "courseHighlights":"placement support",
    "courseBenifit":"frontend developer"
}
###
GET http://localhost:4000/courses-api/getCourses

###
GET http://localhost:4000/courses-api/getCourse/7014

###
PUT http://localhost:4000/courses-api/updateCourse
Content-Type: application/json

{
    "id":7015,
    "courseTitle":"node",
    "courseSylabus":"node js",
    "courseFee":15000,
    "courseDuration":"40 days",
    "courseDates":"2024-05-04",
    "courseHighlights":"real time project training",
    "courseBenfit":"Become a java backend Developer"
}

###
DELETE http://localhost:4000/courses-api/deleteCourses/201
