POST http://localhost:4000/banner-api/createBanner
Content-Type: application/json

{
    "id":8000,
    "bannerImg":"data:image/jpg;base64,IMG20230317094706",
    "bannerTitle":"java programming",
    "bannerSlotDate":"2024-05-05",
    "priority":"10*10 size",
    "status":"underprocess"
}

###
GET http://localhost:4000/banner-api/getBanners

###
GET http://localhost:4000/banner-api/getBanner/801

###
PUT http://localhost:4000/banner-api/updateBanner
Content-Type: application/json

{
    "id":101,
    "bannerImage":"java.png",
    "bannerTitle":"java programming",
    "bannerSlotDate":"05-02-2024",
    "priority":"10*10 size",
    "status":"underprocess"
}

###
DELETE http://localhost:4000/banner-api/deleteBanner/802